WIGLE_TOKEN: "QUlEODRhYjYwNzVjYjI4MTY5ZDU4Yjk2NzQxM2ZiYTFiMDA6YmY2NWE5M2RiYWQ1YzYwNmYwNzdkOTQ2NjE2NmI4MzM="
AMAP_API_KEY: "72dd56ef8ddc4589d3783b4a210caea3"
KEYSTORE_PASSWORD: "LinuxisUbuntu18"
KEY_ALIAS: "suse-app-key"
KEY_PASSWORD: "LinuxisUbuntu18"
